### ISSUE TITLE
UI broken of the webpage

### ISSUE THREAD

**Issue by sagardxd** [celest-dev/website#113]
The middle Header is overlapping the operating system card

![Screenshot 2024-04-30 105441](https://github.com/celest-dev/website/assets/106891027/1989fab5-350e-4f1f-a26f-8f1b398de3ca)

**Comment by dnys1** [comment]
Hi @sagardxd thanks for the heads up! Which operating system and browser did you see this on?

**Comment by dnys1** [comment]
Fixed now :-) Thanks for the heads up!
